name: Build and push

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  IMAGE_NAME: docker.pkg.github.com/shuye-ppsha/psycho-task/psycho-task
  VERSION: latest

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - name: Clonning repo
      uses: actions/checkout@v1
      
    - name: npm installation
      run: npm i
        
    - name: Running tests
      run: npm run test
      
  publish:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    needs: [tests]

    steps:
      - name: Clonning repo
        uses: actions/checkout@v1
          
      - name: Docker login
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin
      - name: Build and push
        run: |
          docker build -f Dockerfile . -t $IMAGE_NAME:$VERSION
          docker push $IMAGE_NAME:$VERSION
